### ISSUE TITLE
Overload `save` and `load` instead of aliasing?

### ISSUE THREAD

**Issue by torfjelde** [JuliaDynamics/DrWatson.jl#105]
Seems to me that `wsave` and `wload` is used everywhere internally for saving and loading files. At the moment these are just aliases for  `FileIO.save` and `FileIO.load` respectively:

https://github.com/JuliaDynamics/DrWatson.jl/blob/28ac0a17c846ab2d96e08b713755ba22805f904a/src/DrWatson.jl#L20-L21

Would it be a good idea to instead do something like
```julia
wsave(args...) = save(args...)
wload(args...) = load(args...)
```
so that the user can overload the saving behavior used internally without overloading `FileIO.save` and `FileIO.load`? E.g. might want to save plots using `Plots.save`, in which case could just implement `wsave(p::Plots.Plot, f) = Plots.savefig(p, f)` and thus, for example, get `safesave` for "free" rather than having to overload `safesave` itself.

I'll can make a PR if this sounds like a good idea.

**Comment by Datseris** [comment]
Yeap, this sounds a good idea, and should have been the original intent.

The reason I wrote `wsave` and `wload` is so that in the initial stages of development we were not bound to FileIO. But you seem to have an excellent point as well :) 

If you notice, other functions like `tmpsave` and `tagsave` etc all call `mkpath` internally and then finally call `wsave`. A good progress would be to make `wsave` call `mkpath` and then call `FileIO.save` (and also overload things like saving plots).

If you're up for making this change that would be awesome.
