### ISSUE TITLE
Add `ignore` to `savename`

### ISSUE THREAD

**Issue by xukai92** [JuliaDynamics/DrWatson.jl#121]
It would be useful to ignore some keys when doing `savename`.

For example

```julia
args = (
    dataset = "mnist",
    n_epochs = 10,
    use_trained = false,
)

savename(args; ignore = [:use_trained]) # => "dataset=mnist_n_epochs=10"
```

**Comment by Datseris** [comment]
Hm, I see where you are coming from.

At the moment is very much possible to do what you want, but from the other way around: you can specify all keys you want to use via the `accesses` keyword. I understand that it would be much more convenient to have to write e.g. one "blacklisted" key instead of six "whitelisted" ones.

The reason I am adding the `discussion` label, is because I think one needs to really think about the `ignore` keyword, and how it would interact `accesses`, because at the moment they contradict each other. 

Some come of "precedence" is certainly necessary. Which should preceede which? Should `ignore` overpower `accesses` or vice versa?

Another way to go about it, which I think is a better way, but takes much more effort to implement, is the following: `ingore` should be implemented like `accesses`, with a default function `allignores(c) = ()`. Then, inside `savename`, the set difference of `access` and `ignore` is taken, and the keys accessed is the result. 

Does this make sense? For the other devs: please feel welcomed to chime in here!

**Comment by xukai92** [comment]
> Some come of "precedence" is certainly necessary. Which should preceede which? Should ignore overpower accesses or vice versa?

I feel "ignore overpower accesses" makes more sense as it is implied by this condition `k in accesses && !(k in ignore)`

> Another way to go about it, which I think is a better way, but takes much more effort to implement, is the following: ingore should be implemented like accesses, with a default function allignores(c) = (). 

I agree with this implementation. I actually did something very similar for my own code, before using DrWaston. See [here](https://github.com/xukai92/MLToolkit.jl/blob/master/src/Scripting/args.jl#L6-L17).

> Then, inside savename, the set difference of access and ignore is taken, and the keys accessed is the result.

By doing so ignore also overpower accesses, right?

**Comment by Datseris** [comment]
> By doing so ignore also overpower accesses, right?

That is correct, because you _remove_ the keys of `accesses` that also exist in `ignore`.

Cool, seems like you already have some experience with this! Maybe you'd like to do a PR that implements this and become a contributor?

**Comment by xukai92** [comment]
Sure. I will a PR soon.
