### ISSUE TITLE
@quickactivate question

### ISSUE THREAD

**Issue by tbeason** [JuliaDynamics/DrWatson.jl#142]
Simple question about `@quickactivate`

Does doing
```
using DrWatson
@quickactivate "MyProj"
```
at the top of my scripts mean that I do NOT need to do
```
activate MyProj
instantiate
```
beforehand? Or is it still needed?

**Comment by Datseris** [comment]
`@quickactivate` **does not** do instantiate. This would be done every time your script runs, which would be terrible, because `instantiate` downloads registry and takes several seconds if not minutes! It only activates, it does not instantiate. 

To improve the docs: how did this question arose? Was there a part of the docs of `quickactivate` that made you think that we also instantiate? I don't see us saying this somewhere, but maybe we say something else missleading.
