### ISSUE TITLE
`jld2` does not work with `wsave` (ArgumentError: keys must be strings)

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaDynamics/DrWatson.jl#160]
I took the example from the documentation `workflow`
https://juliadynamics.github.io/DrWatson.jl/dev/workflow/
and tried to use `jdl2` instead of `bson`.

it throws the error
```julia
ArgumentError: keys must be strings (the names of variables), got a
```

**Comment by sebastianpech** [comment]
We hat this issue before see https://github.com/JuliaDynamics/DrWatson.jl/issues/134
JLD2 doesn't support symbols as dict keys. You can use `@strdict` instead of `@dict`.

**Comment by mmikhasenko** [comment]
thanks for the quick reply.  I thought that `@unpack` would not work with the string keys, but it actually does. For now, everything seems to work with string keys.

A note in the documentation would be super useful.

**Comment by sebastianpech** [comment]
> A note in the documentation would be super useful.

Yeah, that was also the conclusion from the mention issue. ;)

**Comment by Datseris** [comment]
There is a note about this in the documentation: it is the "warning" block at the start of the page https://juliadynamics.github.io/DrWatson.jl/dev/save/ .

Feel free to add the extra text mentioned in the linked issue #134 . I won't do it because I don't believe JLD2 deserves extra special recognition versus any other saving package. We only use BSON because we have to use _a_ example, and it happened to be this.
