### ISSUE TITLE
Macro Hygiene @strdict

### ISSUE THREAD

**Issue by JonasIsensee** [JuliaDynamics/DrWatson.jl#239]
Hi!

I just noticed the following:

```
julia> using DrWatson
[ Info: Precompiling DrWatson [634d3b9d-ee7a-5ddf-bec9-22491ea816e1]

julia> a = 1; b = 2
2

julia> @strdict a b
Dict{String,Int64} with 2 entries:
  "b" => 2
  "a" => 1

julia> @strdict c=b
Dict{String,Int64} with 1 entry:
  "c = b" => 2

julia> c
2

julia> @strdict a=b
Dict{String,Int64} with 1 entry:
  "a = b" => 2

julia> a
2
```

I think that definitely classifies as a bug.
On the other hand, what do you think, would this be a useful feature?
(e.g. renaming variables)

**Comment by Datseris** [comment]
Hi,

`@strdict c=b`, not sure about that, because it is not the syntax declared by the API of `@dict` (which is what `@savename` does). So I wouldn't even call it a "bug", as, well, what is expected to happen, does happen.

> would this be a useful feature?

I did not understand what is the feature here. That you can re-assign values to variables while calling `@strdict` to them?

**Comment by JonasIsensee** [comment]
Hi, 
I naively hope that 
```
julia> @strdict a=b
Dict{String,Int64} with 1 entry:
  "a" => 2

julia> a
1
```

that the assignment syntax would just use the value of the rhs and use the name of the lhs.

Clearly, this is not implemented but I'm wondering if that would be useful.

**Comment by Datseris** [comment]
Aaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaa

yes, this sounds like an excellent feature!
