### ISSUE TITLE
Custom folder structure

### ISSUE THREAD

**Issue by juliohm** [JuliaDynamics/DrWatson.jl#264]
**Is your feature request related to a problem? Please describe.**
I am starting to consider a custom folder structure for a class, and wonder if we can currently customize the structure created by `intiliaze_project`.

**Describe the solution you'd like**
I would like to have some sort of DrWatson.jl settings in `.julia/config/drwatson` that would describe the folder structure and the meaning of each folder, e.g. a "src" folder named "code" or a "notebooks" folder named "apps", etc.

**Describe alternatives you've considered**
I am considering not using DrWatson.jl's initiliaze_project functionality and only use the save/load functionality.

**Comment by Datseris** [comment]
Hm, here is my challenge: it takes much less time, and is much less complicated, to simply rename the created folders and/or create new ones, than to set up such a config file. So why should you go the config file way, instead of the rename-a-folder way?

(to clarify: I'm not "turning down" the suggestion, but merely playing devil's advocate)

**Comment by juliohm** [comment]
These are good questions. I think the main benefit is repeatability. If for some reason I need to do a lot of projects with this custom folder structure, it is much more convenient to have a config for DrWatson.jl than to manually fix things after the fact every time.

**Comment by Datseris** [comment]
For a class, I was thinking that you could initialize a project and set it up as you see fit, and even add packages your students would use, and then send the entire project folder to the class, instead of sharing a config file.

But in general, for a user that wants a specific file structure for all their scientific projects, I guess the config file approach is more efficient. We have discussed this again in another issue (which I unfortunately cannot find now), and if I recall correctly, no-one in the team is opposed to the suggestion. What we would need is someone to implement it in a PR (as the core developers are by definition happy with the current config :P  )

**Comment by juliohm** [comment]
Yes, for a single class it is fine to initialize by hand.

The config file would be for a different, more advanced, scientific audience.

**Comment by Datseris** [comment]
Actually, I'm now challenging myself. Is the config-file approach really more efficient for such a use-case? This person would have to (a) learn how to make such config files, (b) actually create this file and (c) give it to `initialize_project`.

The alternative? (a) copy a drwatson project as-is, (b) rename the folder name and the name in Project.toml to "new project whatever", (c) delete all files in scr/script/whatever folder from the old project.

So I guess it boils down to how hard are the steps (a, b) of the config-approach. Truth be told, I would always go for route 2 even if route 1 was easy. (which is in fact what I do now as all my projects have 2 folders not part of standard structure, and I never "raw" experimental data.)

**Comment by juliohm** [comment]
Consider PkgTemplates.jl as an example. The packages allows great customization of services via templates. So if DrWatson.jl had a couple of templates from the community that would solve the problem. No one wants to spend time doing "non-scientific" management of source code and that is the whole point of DrWatson.jl isn't it? :)

**Comment by Datseris** [comment]
I like your pre-existing templates approach.

**Comment by Datseris** [comment]
A simple basis for the templates, which would keep the syntax as simple as possible, would be a vector
```julia
template = [
"folder1",
"folder2" => ["subfolder1", "subfolder2"],
"folder3",
]
```
DrWatson would always automatically add the Project/Manifest/git folders anyways. Thoughts?

**Comment by juliohm** [comment]
If we had something along the lines of `PkgTemplates.generate_interactive("MyProject")` that would be 👌🏽

**Comment by Datseris** [comment]
@juliohm working on this now. What idea you had for a different template? I'll add a couple pre-made possibilities.

**Comment by juliohm** [comment]
@Datseris I am trying to find the time to reply. Crazy week around here. Feel free to continue with the PR if I don't reply in time. We can always propose new templates later. :)
