### ISSUE TITLE
`@strdict` and `dict_list` with a single parameter do not create a `Dict` of type `{String,Any}`

### ISSUE THREAD

**Issue by hdavid16** [JuliaDynamics/DrWatson.jl#265]
This is an issue because if the output of the simulation is not of the same type as your parameter, then it cannot be saved as described in https://juliadynamics.github.io/DrWatson.jl/dev/workflow/#.-Run-and-save-1

So if my parameter is an integer (for setting a random seed) and my output is a DataFrame. The dataframe cannot be stored in the `Dict` `fulld` because of a type error.

**Comment by Datseris** [comment]
Hi there,

1. Can you paste a MWE?
2. If they don't create a type `Dict{String,Any}`, what do they create?
3. In the example you paste above, in the function `makesim` you wouldn't `copy(d)`, but instead do `fulld = Dict{String,Any}(copy(d))`, which ensures that your dictionary is whatever type you want...

As far as I can tell this isn't really an issue with DrWatson, but a rather simple conversion to `Dict{String,Any}`. If a MWE proves otherwise, feel free to re-open.

**Comment by jolars** [comment]
Actually, creating a Dict{String,Any}, does not help because of #327. See here:

```julia
using DrWatson

params_dict = Dict{String,Any}(
  "sigma" => 0.5,
  "q" => 0.5
)

params_expanded = dict_list(param_dict)

# julia> 1-element Vector{Dict{String, Float64}}:
#   Dict("sigma" => 0.5, "q" => 0.5)
```

It would be nice if #342 was merged.

**Comment by Datseris** [comment]
@jolars feel free to branch off that PR #342  and fix the comments I have and then I'll merge your PR.
