### ISSUE TITLE
function addrun!

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DrWatson.jl#3]
A function `addrun!(csvfile, d)` that adds a simulation/experiment/whatever run to a csv file would be great.

This will allow to make csv tables out of existing simulations. Here is some things that quickly come to mind:

1. The function should operate similarly to `savename`, i.e. allow choosing which keys to save, which types, etc.
2. if the `csvfile` doesn't exist, it creates a new one and adds headers.
3. This function should be able to cooperate with (or even internally create) `DataFrame`.
4. It should somehow allow adding a run that has some _additional_ parameters. How to do this is to be discussed. It could add `missing` entries to all other existing runs that do not have this parameter.
5. As above, when adding a run with _fewer_ parameters, it should add `missing`/NA/Idon'tknowwhat to the parameters that do not exist.

**Comment by Datseris** [comment]
Something important: This function should be "safe". This means that if one submits many jobs into a cluster, and all of them call `addrun!` at the end, it should somehow be safe so that all jobs can add a run into the file instead of some of them erroring because they can't read the file or something?

**Comment by JonasIsensee** [comment]
Have a look at my function `update_results` 
in `scripts/symmetry/update_results.jl` in the gitlab repo.
It doesn't have a whole lot of comments yet but the general structure should be recognizable.

When called it 
 1) tries to open `data/results_dataframe.jld2` or creates a new `DataFrame`
 2) Then walks through `data/results/` and searches for new `.jld2` files that are not in the dataframe yet ( where each .jld2 file represents results from a single run.
 3) accepts arguments `white_list`, `black_list`, `special`


black_list is a list of keys of the .jld2 to ignore
special is a list of pairs (key => data -> func(data)) 
where a new column `key` has the value returned from `func`

and if `white_list` passed only the elements in white_list will be used (instead of all by default)

**Comment by JonasIsensee** [comment]
Using `.csv` files only makes sense when your results + parameters are a bunch of numbers
and no types or arrays and such. 
In the more complex case I don't see the point in converting between `.csv` textfile
and julia back and forth

**Comment by Datseris** [comment]
You may have misunderstood: 

The csv table that `addrun!` will create exists only to list whether a simulation has _run_ or not. It does not exist to store the actual results of the simulations! For this kind of setting, a text file is important because it is **human readable**. (Also, it doesn't have to use FileIO, which is another plus.)

In addition, exactly because it is a text file, it is fast to check whether you have already run a simulation or not by reading the text file instead of the `.jld2` file.

---

Thanks a lot for sharing this function, I will look at it in detail. Seems also very helpful and I believe that what you have described definitely fits the scope of DrWatson.

I will look at it in action as well, by checking the folder that it is currently used and see how it operates. I think I will even open a new issue about it to keep the conversation clean.

**Comment by Datseris** [comment]
@mauro3 also had some arguments why a text-only aproach is useful. These are of course long lost in Slack, but @mauro3 maybe you want to repeat them here?

**Comment by Datseris** [comment]
Hey @JonasIsensee , do you want to PR the functionality you described in your comment: https://github.com/JuliaDynamics/DrWatson.jl/issues/3#issuecomment-463701752  ? It is very useful in general and maybe it will be easy for me to modify it such that it can do similar with a text file.

**Comment by JonasIsensee** [comment]
Will do some time next week.
