### ISSUE TITLE
v2.12.2 breaks compatibility of produce_or_load() and datadir()

### ISSUE THREAD

**Issue by judober** [JuliaDynamics/DrWatson.jl#382]
**Describe the bug**
When using `produce_or_load(datadir("sims"), myparams, myfun)`  in v2.12.2 (.1 works fine) I get the error
```
MethodError: no method matching produce_or_load(::SubString{String}, ::Dict{String, Any}, ::typeof(myfun))
```

It seems that a String instead of the SubString would work.
Maybe related to #380 ?

**Minimal Working Example**
Sorry, I have no MWE yet.

```
julia> versioninfo()
Julia Version 1.8.5
Commit 17cfb8e65e (2023-01-08 06:45 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, tigerlake)
  Threads: 8 on 8 virtual cores
Environment:
  JULIA_EDITOR = code
```

**Comment by judober** [comment]
In 2.12.1:
```
typeof(datadir("sims")) == String
```
In 2.12.2:
```
typeof(datadir("sims")) == SubString{String}
```
This seems to be incompabitle with `produce_or_load`.

So I guess either `produce_or_load` should accept a SubString or `datadir` should return a String.

**Comment by Tom271** [comment]
I hit this issue yesterday. A quick fix is to do `String(datadir("sims"))`. It also causes an issue with `save` using CairoMakie as that also requires a String. So fixing `produce_or_load` (by as @judober said changing the function signature to AbstractString so that Substring and String work), would not fix the whole issue.  I'd suggest @judober's second fix, modifying the `*dir()` functions to output a string.
