### ISSUE TITLE
tag with git commit message

### ISSUE THREAD

**Issue by harrybooth** [JuliaDynamics/DrWatson.jl#387]
Maybe I have overlooked this functionality, but would it be possible to add the git commit message to the result dictionary using [DrWatson.@tag!](https://juliadynamics.github.io/DrWatson.jl/v0.8/save/#DrWatson.@tag!)?

This would be really useful, as for example the git commit hash e.g. gitcommit => "96df587e45b29e7a46348a3d780db1f85f41de04" is non-descriptive, especially if you are trying to compare different versions of the same data and understand what the change was. Allowing the git commit message to be included, e.g. "changed parameter x to y" would be a nice automated way to relate code changes to experimental results.

**Comment by Datseris** [comment]
Sure, this seems like providing a keyword arugment `use_description = false` to `tag!`. If `true`, the commit description is used instead of the tag. Note that this is dangerous: commit descriptions can be arbitrarily small and non-unique, so this may not really help you reverse time and go back to given commit. But of course use at your own risk hence the default value will be `false`.

**Comment by Datseris** [comment]
sure

**Comment by Datseris** [comment]
we can do it like the `gitpatch` keyword: the commit message can be added as an additional field instead of replacing or mingling with the git commit field
