### ISSUE TITLE
Question about packages used inside a module for DrWatson

### ISSUE THREAD

**Issue by martinmestre** [JuliaDynamics/DrWatson.jl#401]
Hi, thank you very much for your great package. I am implementing the suggestion to use a module as a packages doing:
`@quickactivate :MyModule`
I thought that if I have added Reexport in the global environment, it would be possible to not add it in local env that `@quickactivate` activates. But it seems that I need to add Reexport explicitly in the local env. Is that right? 
Besides, in you example, why do you do the following commands:
```
using NCDatasets: NCDataset, dimnames, NCDatasets
export NCDataset, dimnames
```
Thank you very much,
best

**Comment by Datseris** [comment]
Hi, you are welcome. 

> I thought that if I have added Reexport in the global environment, it would be possible to not add it in local env that `@quickactivate` activates

No, it is mandatory to explicitly add in the local environment all the packages you want to use in this environment. This goes for Reexport or anything else. (and even if it wasn't I would still recommend it for clarity)

> Besides, in you example, why do you do the following commands:
> 
> ```
> using NCDatasets: NCDataset, dimnames, NCDatasets
> export NCDataset, dimnames
> ```

I do this because I only want to explicitly export these two names after the `export`. Does this answer your question, or have I not understood it? If I have not understood the second question, can you please rephrase it?

**Comment by martinmestre** [comment]
Hello @Datseris , thank you very much for your answers. Regarding the second question, I will rephrase  it in two questions:

1) I see you are doing something like
`using A: x, y, A`
where `A=NCDatasets`. Why do you write the package `A` twice ?

2) Why don't you use Reexport also for that package like:
`@reexport using A: x, y`

Thank you very much again, Best.

**Comment by martinmestre** [comment]
Understood, thank you very much!
