### ISSUE TITLE
Default arguments / config file for DrWatson

### ISSUE THREAD

**Issue by asinghvi17** [JuliaDynamics/DrWatson.jl#59]
It would be great to be able to create local (and global) configuration files for DrWatson.  Ideally, these config files would be able to set default prefixes, suffixes and separators, as well as file formats.  I'm not sure what the best way to implement this is, though.

**Comment by Datseris** [comment]
I am not sure at which part of the DrWatson functionality you are referring here. Is it the functions used in `savename`?

These are extendable via multiple dispatch. You don't need a text file, you can just do it in your project's source code. You can still extend `Any` and then you just change the "default behavior" for everything.

What is the advantage of using one additional text-based configuration file instead of the native approach of multiple dispatch? At the moment I don't see something.

**Comment by asinghvi17** [comment]
I wasn't thinking of a text file specifically, and the approach of just having Julia code run works; you can put it, for example, in `intro.jl`.  Thanks!
