### ISSUE TITLE
Suggestion: Use PkgTemplates.jl to generate Project.toml?

### ISSUE THREAD

**Issue by singularitti** [JuliaDynamics/DrWatson.jl#89]
The [DrWatson.jl](https://github.com/JuliaDynamics/DrWatson.jl) generated Project.toml is not well-formatted and no CI/CD supports:
```julia
julia> using DrWatson

julia> initialize_project("MMM", authors="me")
Activating new environment at `~/Downloads/MMM/Project.toml`
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
  Updating `~/Downloads/MMM/Project.toml`
  [634d3b9d] + DrWatson v1.0.1
  Updating `~/Downloads/MMM/Manifest.toml`
  [634d3b9d] + DrWatson v1.0.1
  [5789e2e9] + FileIO v1.0.7
  [ae029012] + Requires v0.5.2
  [2a0f44e3] + Base64 
  [ade2ca70] + Dates 
  [8ba89e20] + Distributed 
  [b77e0a4c] + InteractiveUtils 
  [76f85450] + LibGit2 
  [56ddb016] + Logging 
  [d6f4376e] + Markdown 
  [44cfe95a] + Pkg 
  [de0858da] + Printf 
  [3fa0cd96] + REPL 
  [9a3f8284] + Random 
  [ea8e919c] + SHA 
  [9e88b42a] + Serialization 
  [6462fe0b] + Sockets 
  [8dfed614] + Test 
  [cf7118a7] + UUIDs 
  [4ec0a83e] + Unicode 
"MMM"
```
Project.toml:
```toml
name = "MMM"
authors = ["me"]
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
```
While [PkgTemplates.jl](https://github.com/invenia/PkgTemplates.jl) generated Project.toml looks much better and has CI/CD/documentation/license supports:
```julia
julia> t = Template(;
                  user="xxxx",
                  license="MIT",
                  authors=["me"],
                  julia_version=v"1.0",
                  ssh=true,
                  plugins=[
                      TravisCI(),
                      Codecov(),
                      Coveralls(),
                      AppVeyor(),
                      GitHubPages(),
                      CirrusCI(),
                  ],
              )
Template:
  → User: xxxx
  → Host: github.com
  → License: MIT (me 2019)
  → Package directory: ~/.julia/dev
  → Minimum Julia version: v1.0
  → SSH remote: Yes
  → Add packages to main environment: Yes
  → Commit Manifest.toml: No
  → Plugins:
    • AppVeyor:
      → Config file: Default
      → 0 gitignore entries
    • CirrusCI:
      → Config file: Default
      → 0 gitignore entries
    • Codecov:
      → Config file: None
      → 3 gitignore entries: "*.jl.cov", "*.jl.*.cov", "*.jl.mem"
    • Coveralls:
      → Config file: None
      → 3 gitignore entries: "*.jl.cov", "*.jl.*.cov", "*.jl.mem"
    • GitHubPages:
      → 0 asset files
      → 2 gitignore entries: "/docs/build/", "/docs/site/"
    • TravisCI:
      → Config file: Default
      → 0 gitignore entries

julia> generate(t, "MMM");
```
will generate a lot of files
```
.
├── LICENSE
├── .appveyor.yml
├── .cirrus.yml
├── .gitignore
├── .travis.yml
├── Manifest.toml
├── Project.toml
├── README.md
├── docs
│   ├── Manifest.toml
│   ├── Project.toml
│   ├── make.jl
│   └── src
│       └── index.md
├── src
│   └── MMM.jl
└── test
    └── runtests.jl

4 directories, 10 files
```
The Project.toml looks especially better:
```toml
name = "MMM"
uuid = "0ca299d9-6e6b-49b5-857c-f01b2625cc38"
authors = ["me"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
Could we switch to use PkgTemplates.jl to generate these files?

**Comment by Datseris** [comment]
Hm, 

What is the benefit of having these extra files:
```
├── LICENSE
├── .appveyor.yml
├── .cirrus.yml
├── .travis.yml
├── docs
│   ├── Manifest.toml
│   ├── Project.toml
│   ├── make.jl
│   └── src
│       └── index.md
└── test
    └── runtests.jl
```
for a scientific project?

In addition, what is the benefit of having:

```
uuid = "0ca299d9-6e6b-49b5-857c-f01b2625cc38"
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
```
In your project.toml, for a scientific project? And *crucially*, what does UUID or `version` even mean for a scientific project?

I have tried to stress this in DrWatson's documentation: DrWatson is not supposed to help you make a Julia package. Its only concern are scientific projects, which only care about a `Project.toml` and its dependencies (and the inevitable Manifest.toml of course). At the moment I don't see any use for all these extra stuff, as their purpose is 100% oriented in making a Julia package, and don't offer anything extra for the actual project.

Since it is not clear from the docs that DrWatson is not a tool to develop Julia packages, could you please help me by providing feedback on where in the documentation this information will be most visible?

---

There is one thing in the code you paste that is indeed very important, but _not_ done at the moment by `initialize_project`, that is the entry 

```
[compat]
julia = "x.y"
```
with `x.y` the Julia version under use when calling `initialize_project`. This we **must** add, and let me know if you want to do a small PR for it.

**Comment by tamasgal** [comment]
I also think that a `DrWatson` project is just a project and not a package. I usually do spin-off packages when I end up with functions/types/whatever which I would like to share across different projects/packages and then add those to the `Project.toml`.

**Comment by singularitti** [comment]
> What is the benefit of having these extra files:
> 
> ```
> ├── LICENSE
> ├── .appveyor.yml
> ├── .cirrus.yml
> ├── .travis.yml
> ├── docs
> │   ├── Manifest.toml
> │   ├── Project.toml
> │   ├── make.jl
> │   └── src
> │       └── index.md
> └── test
>     └── runtests.jl
> ```
> 
> for a scientific project?

Why cannot a project has CI/CD support? The project does have `src/` folder, so what prevents it from having a `test`? I do have 2 scientific projects, hosted on GitHub (private), built/tested on Travis CI (because my accounts for GitHub and Travis are educational and thus free to build private repositories). Some people may have the same use case as mine. Even they are private now, one day I may want them all public, then CIRRUS and AppVeyor can build them also. In addition, what prevents me from testing/building my projects on various environments, before sharing it to my colleagues (who probably use different OSs, architectures, and Julia versions)?

> In addition, what is the benefit of having:
> 
> ```
> uuid = "0ca299d9-6e6b-49b5-857c-f01b2625cc38"
> version = "0.1.0"
> 
> [extras]
> Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
> 
> [targets]
> test = ["Test"]
> ```
> 
> In your project.toml, for a scientific project? And _crucially_, what does UUID or `version` even mean for a scientific project?

I might have a group of students who use Julia to manage their homework, and each of them set up a project with the same name (e.g., the course's name), but they definitely want to have different UUID for their projects, right?
For the version thing, that is simple. We can tag the `version` with `2019.1.3` means that was done by Jan, 3rd, 2019. Or we could simply let it be `2019.1`, which means the project up to Jan, 2019, to discourage over-tagging projects. This tagging system has been applied to a lot of successful software, such as [pipenv](https://github.com/pypa/pipenv) (latest version `2018.11.26`), [PyCharm](https://www.jetbrains.com/pycharm/) (latest version `2019.2.3`), [mactex](http://www.tug.org/mactex/) (latest version `2019.0508`).

**Comment by singularitti** [comment]
What I did not mention is the default Project.toml's formatting is pretty bad:
```toml
name = "MMM"
authors = ["me"]
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
```
It at least needs some empty lines above `[deps]` field. If we do one thing, why do not do it better?

**Comment by Datseris** [comment]
Your comments on the CI files support appear too specific for your style of work and use-case, and unfortunately they are not convincing me to make such a change. All of these files can be just added by you manually. I also manually create a `documents` folder in most of my repos and put my to-do lists there, but I don't think it is general enough to make a change for everyone. 

Besides, no-one is forcing you to use `initialize_project`, you could use PkgTemplate.jl at any point. The documentation of DrWatson is quite clear about how it works, and thus it should be obvious that `initialize_project` is just optional.

> but they definitely want to have different UUID for their projects, right? 

No. A project is not a julia package, you can't do `using This science project I am working on`. You can't call `using` on any arbitrary julia project and thus UUID is meaningless in the use cases that DrWatson targets.

> For the version thing, that is simple. We can tag the version with 2019.1.3, which means it was done by Jan, 3rd, 2019. 

There is no meaning for me to have a version for a scientific project because once again **it is not a Julia package**. The Git tags and git commits are more than enough for any human-readable versioning purposes.

---

> What I did not mention is the default Project.toml's formatting is pretty bad:

It's the second time you've used the word "bad" by now, yet I have not seen you open any PRs to improve this "bad" situation. As I mentioned, the Project.toml could be improved by adding the julia compat line, 

```
[compat]
julia = "x.y"
```

and also, to the best of my knowledge empty lines do not really affect the parsing of `Project.toml`.

---

As I do not see any reason to use PkgTemplate.jl inside DrWatson, and since you can at any point initialize your project using PkgTemplate.jl instead of `initialize_project`, I am closing this. The only thing that can be added is now a separate issue #91 .

**Comment by singularitti** [comment]
> Your comments on the CI files support appear too specific for your style of work and use-case, and unfortunately they are not convincing me to make such a change. All of these files can be just added by you manually. I also manually create a `documents` folder in most of my repos and put my to-do lists there, but I don't think it is general enough to make a change for everyone.

Was it too specific to me? Or was it too fast you close this so-called "discussion" that no other people have time to make them heard? At least one other user did say "project is just a project and not a package", and you did not "discuss" with him. Right, I can add them manually. But why should I do it every time? I could write a script but why cannot this function provided by `initialize_project`? It can be optional whether you want to set up CI/CD or test, just make them default `false`.

> Besides, no-one is forcing you to use `initialize_project`, you could use PkgTemplate.jl at any point. The documentation of DrWatson is quite clear about how it works, and thus it should be obvious that `initialize_project` is just optional.

I know this is optional and is not required. I just think it could be more versatile. If I write everything myself, why do I even use DrWatson.jl? And do not imply me I did not read your documentation.

> There is no meaning for me to have a version for a scientific project because once again **it is not a Julia package**. The Git tags and git commits are more than enough for any human-readable versioning purposes.

What prevents it from being a Julia package?

> It's the second time you've demonstrated how "bad" or "not well-formatted" this file is, yet I have not seen you open any PRs to improve this "bad" situation. As I mentioned, the Project.toml could be improved by adding the julia compat line,

I do have duty to make a PR, just as you do not have a duty to accept my gripe. A gripe is not a very bad thing to a community. I am just "make myself heard", and I could contribute if I have time.

> and also, to the best of my knowledge empty lines do not really affect the parsing of `Project.toml`.

I do not mention anything about parsing. It is just not good-looking (compared to that generated by PkgTemplates.jl).

**Comment by tamasgal** [comment]
Ok pals, let us focus 😆 

Let me come back to the original issue(s)...

First: the formatting of the `Project.toml` is not nice, so the message, which is just adding some whitespace. I think that's a low hanging fruit for a first PR and does not take a lot of time.

Second: you tend to compare `DrWatson` with `PkgTemplates` and I think there you hit a nerve, since `DrWatson` is really just meant for managing scientific projects and I would stay with the philosophy "one thing well". Everything else can be added by taste and I think it's not a big deal.

I'd also like to mention that I am totally a CI/CD guy (besides the fact that I am a physicist) and I am even the one who fought years to get a my scientist colleagues (we are 300 people) into the habit of automated tests and (don't laugh) version management at all. So I understand that you want to have this standardised in the template.

I rather have another suggestion instead of pulling in `PkgTemplates` as a dependency: why not making a plugin for `PkgTemplates` instead? I mean, `PkgTemplates` does "one thing well", namely setting up a package, where testing is mandatory and we would not duplicate the effort.
However, I also have the feeling that it will a bit diverge from what `DrWatson` is for, but on the other hand, it's decoupled and people are free to decide how to dive in and get a solid base to start off.

**Comment by singularitti** [comment]
> I rather have another suggestion instead of pulling in `PkgTemplates` as a dependency: why not making a plugin for `PkgTemplates` instead? I mean, `PkgTemplates` does "one thing well", namely setting up a package, where testing is mandatory and we would not duplicate the effort.
> However, I also have the feeling that it will a bit diverge from what `DrWatson` is for, but on the other hand, it's decoupled and people are free to decide how to dive in and get a solid base to start off.

Good idea. I have not made any plugin for a Julia package yet. How to do it?

**Comment by Datseris** [comment]
https://invenia.github.io/PkgTemplates.jl/stable/pages/plugin_development/
